from pptx import Presentation
import os

def generate_markdown_report(topic, trends, summaries):
    """Creates a structured academic report in Markdown."""
    report = f"# Research Report: {topic}\n\n"
    report += "## Abstract\nAutomated synthesis of current literature.\n\n"
    report += f"## Key Trends & Analysis\n{trends}\n\n"
    report += "## Literature Review & Summaries\n"
    for s in summaries:
        report += f"{s}\n\n"
    return report

def generate_presentation(topic, trends, filename):
    """Creates a PowerPoint presentation with key insights."""
    prs = Presentation()
    
    # Title Slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = topic
    slide.placeholders[1].text = "Generated by AI Autonomous Research Assistant"

    # Trends Slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Key Research Trends"
    slide.placeholders[1].text = trends[:1000] # Basic truncation for slide fit

    # Ensure output directory exists
    output_path = os.path.join("outputs", filename)
    prs.save(output_path)
    return output_path